version: '3'

services:
  reverse-proxy:
    image: traefik:v2.3
    restart: always
    command: >
      --api.dashboard=true
      --providers.docker
      --providers.docker.exposedByDefault=false
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-router.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik-router.service=api@internal"
      - "traefik.http.middlewares.traefik-dashboard.addprefix.prefix=/dashboard/"

networks:
  traefik:
    external: true
